dist: xenial
language: shell

addons:
  snaps:
  - name: snapcraft
    classic: true
  - name: multipass
    classic: true
    channel: beta
    
script:
  - /snap/bin/snapcraft clean
  - travis_wait 50 /snap/bin/snapcraft --target-arch amd64
