dist: xenial
language: shell

addons:
  snaps:
  - name: snapcraft
    classic: true
    
script:
  - sudo apt update
  - /snap/bin/snapcraft clean
  - travis_wait 50 /snap/bin/snapcraft --target-arch amd64
