dist: xenial
language: shell

addons:
  snaps:
  - name: snapcraft
    classic: true
    
script:
  - while sleep 5m; do echo "=====[ $SECONDS seconds, buildroot still building... ]====="; done &
  - sudo apt update
  - /snap/bin/snapcraft clean
  - /snap/bin/snapcraft --target-arch amd64
